# For deploying on a (physical) server
# Simply download this file and start it with 'docker-compose up -d'
version: "3.7"

services:
  embedding:
    container_name: embedding-api
    image: europeana/embedding-api:main
    environment:
      EXECUTOR_MAX_INSTANCE: 4
    deploy:
      resources:
        limits:
          memory: 16G           
    healthcheck:
      test: curl --fail http://localhost:8080/actuator/health || exit 1
      interval: 10s
      start_period: 20s
      timeout: 20s
      retries: 3
    restart: on-failure      
    ports:
    - "80:8080"
    - "8080:8080"

