apiVersion: apps/v1
kind: Deployment
metadata:
  name: embedding-api-deployment
spec:
  # selector.matchLabels is provided via Kustomize
  template:
    spec:
      containers:
        - name: myapi
          image: europeana/embedding-api
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              port: 8080
              path: /actuator/health/liveness
            initialDelaySeconds: 60
            periodSeconds: 30
          readinessProbe:
            httpGet:
              port: 8080
              path: /actuator/health/readiness
            initialDelaySeconds: 60
            periodSeconds: 30
          volumeMounts:
            - name: secret
              mountPath: "/usr/local/tomcat/webapps/ROOT/WEB-INF/classes/embedding.user.properties"
              readOnly: true
              subPath: embedding.user.properties
      volumes:
        - name: secret
          secret:
            secretName: embedding-api-secret