apiVersion: apps/v1
kind: Deployment
metadata:
  name: embedding-api2-deployment
spec:
  template:
    spec:
      containers:
        - name: embedding-api2
          # required to use local image
          imagePullPolicy: Never